name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: cd portfolio && npm install
      - run: cd portfolio && npm run lint
      - run: cd portfolio && npm test
      - run: cd portfolio && npm run build 